### PR TITLE
fix: update a require path from bin/duck

### PR DESCRIPTION
**Pull request by koba04**
Currently, `duck` is being broken by the following error.

> Error: Cannot find module '../lib/src/cli'

This seems to be introduced by https://github.com/teppeis/duck/commit/89c18dabd6f4768b972e9f46486a62ba857cd0d0

### CODE REVIEW

**Comment by teppeis** [comment]
@koba04 Oh, this is a critical bug... 😿
Released in v0.17.2.
Thank you!

**Comment by teppeis** [comment]
@koba04 I've invited you to this github repo and the npm package. Feel free to fix and publish yourself!

**Comment by koba04** [comment]
@teppeis Thanks!!!
